name: Docker
on:
  push:
    branches:
      - master

jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Building docker
      run: |
        docker build .
